// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swhtppbysnpixgwmvssr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3aHRwcGJ5c25waXhnd212c3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDA4MTYsImV4cCI6MjA2MzM3NjgxNn0.XH-jvNcNM9fSRH0_4S0AYxKc1mPP-TxS7vjU5Mc-oR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);